name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/fred/public_html/ingeltechgh.com/boobae_api
          /usr/local/bin/pm2 stop boobae_api
          /usr/bin/git pull
          /usr/local/bin/npm install
          /usr/local/bin/pm2 start boobae_api


